version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12.0
      # - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: update-npm 
          command: 'sudo yarn global add yarn@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-yarn-wee
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: 'yarn test:ci'
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
